version: '3'

services:
  db_postgres:
    container_name: 'db_order'
    image: 'postgres:12.6-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./database/order:/var/lib/postgresql/data/

  be_order:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db_postgres
    links:
      - db_postgres

  be_order_test:
    container_name: 'be_test_order'
    command: echo 'Test container ready'
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db_postgres
    links:
      - db_postgres
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
