export enum OrderStatus {
  BOOKING = 'BOOKING',
  BOOKING_SUCCESSED = 'BOOKING_SUCCESSED',
  WAITING_FOR_APPROVEMENT = 'WAITING_FOR_APPROVEMENT',
  CANCELLING = 'CANCELLING',
  CANCELLED = 'CANCELLED',
  FINISHED = 'FINISHED',
}
