export enum OrderStatus {
  CREATED = 'CREATED',
  BOOKING = 'BOOKING',
  BOOKING_SUCCESSED = 'BOOKING_SUCCESSED',
  BOOKING_FAILED = 'BOOKING_FAILED',
  WAITING_FOR_APPROVEMENT = 'WAITING_FOR_APPROVEMENT',
  CANCELLING = 'CANCELLING',
  CANCELLED = 'CANCELLED',
  CANCELL_FAILED = 'CANCELL_FAILED',
  FINISHED = 'FINISHED',
}
